elanelsystem/sales/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from configuracion import views
from .views import *
from .utils import exportar_excel  # Importa la función de exportación
from .views import GraficosDashboard,DashboardColaboradores
from .views import ventas_analytics_api, exportar_ventas_excel, exportar_pagos_cannon_excel
from .views import graficos
app_name="sales"

urlpatterns = [

    path("resumen/",Resumen.as_view(),name="resumen"),

    #region URLs Ventas ----------------------------------
    path("ventas/importar/",importVentas,name="importVentas"),
    path("ventas/cliente/<int:pk>/crear_venta/",CrearVenta.as_view(),name="create_sale"),
    path("ventas/get_vendedores_supervisores/",requestVendedores_Supervisores,name="requestVendedores_Supervisores"),
    path("ventas/detalles", VentasDetalles.as_view(),name="detallesVentas"),
    path("ventas/detalle_venta/<int:pk>/",DetailSale.as_view(),name="detail_sale"),

    path("ventas/detalle_venta/<int:pk>/eliminar_venta/",eliminarVenta,name="delete_sale"),
    path("ventas/detalle_venta/descuento_cuota/",aplicarDescuentoCuota,name="descCuota"),
    path("ventas/detalle_venta/get_specific_cuota/",getUnaCuotaDeUnaVenta,name="getCuota"),
    path("ventas/detalle_venta/pay_cuota/",pagarCuota,name="payCuota"),
    # path("ventas/detalle_venta/anular_cuota/",anularCuota,name="anularCuota"),

    path("ventas/detalle_venta/<int:pk>/dar_baja/",darBaja,name="darBaja"),
    path("ventas/<int:pk>/adjudicacion/sorteo/",CreateAdjudicacion.as_view(),name="adjSorteo"),
    path("ventas/<int:pk>/adjudicacion/negociacion/",CreateAdjudicacion.as_view(),name="adjNegociacion"),
    path("ventas/<int:pk>/cambiopack",ChangePack.as_view(),name="cambioPack"),
    path("ventas/<int:pk>/cambiotitularidad",ChangeTitularidad.as_view(),name="changeTitu"),
    path("ventas/ventas_suspendidas",PanelVentasSuspendidas.as_view(),name="ventasSuspendidas"),
    path("ventas/simulador_plan_recupero/<int:pk>/",SimuladorPlanRecupero.as_view(),name="simuladorPlanrecupero"),
    path("ventas/crear_plan_recupero/<int:pk>/",PlanRecupero.as_view(),name="planRecupero"),
    
    path("ventas/detalle_venta/solcitud_anulacion_cuota/",solicitudBajaCuota,name="solicitudAnulacionCuota"),
    path('ventas/detalle_venta/autorizar-baja/<int:ventaID>/<str:cuota>/', darAutorizacionBajaCuota, name='autorizar_baja_cuota'),
    path('ventas/detalle_venta/pagina_confirmacion_baja_cuota/', pagina_confirmacion, name='pagina_confirmacion_baja_cuota'),
    path('ventas/detalle_venta/confirma-baja-cuota/', darBajaCuota, name='darBajaCuota'),

    path('ventas/comisionables/',VentasComisionables.as_view(),name='ventas_comisionables'),
    # endpoint AJAX para toggle
    path('ventas/comisionable-toggle/',toggle_comisionable,name='toggle_comisionable'),
    # endpoint para el dashboard de gráficos
    path('graficos/', GraficosDashboard.as_view(), name='graficos'),
    path('graficos/cannon/', graficos_pagos_cannon, name='graficos_cannon'),
    path('dashboard/colaboradores/', DashboardColaboradores.as_view(), name='dashboard_colaboradores'),
    path('api/autocomplete-colaborador/', autocomplete_colaborador, name='autocomplete_colaborador'),
    path('api/ventas-colaborador/', ventas_colaborador, name='ventas_colaborador'),
    path('api/ventas-analytics/', ventas_analytics_api, name='ventas_analytics_api'),
    path('api/pagos-cannon-analytics/', pagos_cannon_analytics_api, name='pagos_cannon_analytics_api'),
    path('api/exportar-ventas-excel/', exportar_ventas_excel, name='exportar_ventas_excel'),
    path('api/exportar-pagos-cannon-excel/', exportar_pagos_cannon_excel, name='exportar_pagos_cannon_excel'),
    #endregion ----------------------------------------------------------

    #region URLs Caja -----------------------------------------------------
    path("ventas/caja/",Caja.as_view(),name="caja"),
    path("arqueo/", CierreCaja.as_view(), name="arqueo"),
    path("arqueo/old/", OldArqueosView.as_view(), name="oldArqueos"),
    path("arqueo/saldo/", ArqueoSaldoAPI.as_view(), name="arqueoSaldo"),

    path("ventas/movs_pagos/", movs_pagos_list_api, name="movs_pagos_list"),
    path("ventas/movs_pagos/<str:kind>/<int:pk>/", movs_pagos_detail_api, name="movs_pagos_detail"),
    #endregion -----------------------------------------------------------
    
    #region URLs PDFs ------------------------------------------------------
    path("ventas/pdf/baja/<int:pk>",viewsPDFBaja,name="bajaPDF"),
    path("ventas/pdf/titularidad/<int:pk>/<int:idCambio>",viewPDFTitularidad,name="tituPDF"),
    path("ventas/pdf/arqueo/<int:pk>/",viewPDFArqueo,name="arqueoPDF"),
    path("ventas/pdf/informe/", viewsPDFInforme, name="ventas_pdf_informe"),
    path("ventas/excel/informe/", viewsExcelInforme, name="ventas_excel_informe"),
    # path('ventas/detalle_venta/recibo/pago/<int:pk>/', viewPDFReciboCuota, name='getReciboCuota'),
    #     path(
    #     "ventas/detalle_venta/recibo-json/pago/<int:pk>/",
    #     recibo_pago_json,
    #     name="recibo-pago-json"
    # ),
    path('ventas/detalle_venta/recibo-preview/<int:pk>/', recibo_preview, name='recibo-preview'),
    #endregion ---------------------------------------------------------
        
    #region URLs PostVentas --------------------------------------------
    path("ventas/postventas/", PostVenta.as_view(), name="postVentaList"),
    path("ventas/auditorias/api/", auditorias_api, name="auditorias_api"),
    path("ventas/auditorias/crear/", crear_auditoria, name="crear_auditoria"),
    path('ventas/postventas/informe/', viewsPDFInformePostVenta, name='postVentaPDF'),
    #endregion ---------------------------------------------------------
    
    #region URLs Specifics Functions ------------------------------------------------------------
    # path('ventas/detalles/', requestDetallesVentas, name='requestDetallesVentas'),
    # path('ventas/request_ventas/', requestVentasAuditoria, name='requestVentasAuditorias'),

    path('requestmovs/', requestMovimientos, name='rmovs'),
    path('create_new_mov/', createNewMov, name='create_new_mov'),
    #endregion --------------------------------------------------------------------------------

    path("api/cotizaciones/dolar/", cotizaciones_dolar, name="cotizaciones_dolar"),
]

elanelsystem/users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *
 
app_name="users"

urlpatterns = [
    path("usuario/api/me/", me, name="me"),

    path("usuario/crear_usuario/",CrearUsuario.as_view(),name="create_user"),
    path("usuario/search/",requestUsuarios2,name="searchUsers"),

    path("usuario/lista_usuarios/",ListaUsers.as_view(),name="list_users"),
    path("cliente/importUsuarios/",importar_usuarios,name="importUsuarios"),
    path("usuario/aplicar_descuento/",realizarDescuento,name="realizarDescuento"),
    path("usuario/detalleusuario/<int:pk>/",DetailUser.as_view(),name="detailUser"),
    path("cliente/lista_clientes/",ListaClientes.as_view(),name="list_customers"),
    path("cliente/importClientes/",importar_clientes,name="importClientes"),
    path("usuario/administracion/requestusuarios/",requestUsuarios,name="requestUsuarios"),
    path("cliente/crear_cliente/",CrearCliente.as_view(),name="create_customer"),
    path("cliente/<int:pk>/operaciones/",CuentaUser.as_view(),name="cuentaUser"),
    path("usuario/administracion/",PanelAdmin.as_view(),name="panelAdmin"),
    path("usuario/administracion/permisos/",PanelPermisos.as_view(),name="panelPermisos"),
    path("usuario/configurar_perfil/",ConfiguracionPerfil.as_view(),name="configurarPerfil"),


    #region Sucursal CRUD - - - - - - - -
    path("usuario/administracion/sucursales/",PanelSucursales.as_view(),name="panelSucursales"),
    path("usuario/administracion/sucursales/add",addSucursal,name="addSucursal"),
    path("usuario/administracion/sucursales/remove",removeSucursal,name="removeSucursal"),
    path("usuario/administracion/sucursales/update",updateSucursal,name="updateSucursal"),
    #endregion - - - - - - - - - - - - - - 

    #region Cuenta de cobros CRUD - - - - - - - -
    path("usuario/administracion/cuentas_cobros/",PanelCuentaCobro.as_view(),name="panelCuentaDeCobro"),
    path("usuario/administracion/cuentas_cobros/add",addCuenta,name="addCuenta"),
    path("usuario/administracion/cuentas_cobros/remove",removeCuenta,name="removeCuenta"),
    #endregion - - - - - - - - - - - - - - 

    #region Permisos - - - - - - -  - - - - - - - - - - - -
    path("usuario/administracion/requestpermisos/",requestPermisosDeGrupo,name="requestPermisos"),
    path("usuario/administracion/updatepermisos/",updatePermisosAGrupo,name="updatePermisos"),
    path("usuario/administracion/createnewgroup/",createNewGroup,name="newGroup"),
    path("usuario/administracion/deletenewgroup/",deleteGrupo,name="deleteGroup"),
    path("usuario/administracion/requestkey/",requestKey,name="requestKey"),
    #endregion  - - - - - - - - - - - - - - - - - - - - - - - -

    path("usuario/pdf/ficha_creacion/<int:pk>",viewsPDFNewUser,name="newUserPDF"),

]

elanelsystem/templates/detalle_por_datos.html
{% extends 'molde.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/detallesDatosDeNegocio.css' %}">
<link rel="stylesheet" href="{% static 'css/root_base.css' %}">
<link rel="stylesheet" href="{% static 'modalStatic/doc/tingle/tingle.min.css' %}">

{% endblock css %}

{% block content %}
<div id="wrapperLoader">
  <span id="loader"></span>
</div>

<div class="filters">
  
  <form method="POST" id="formFilter">
    {% csrf_token %}
    <div class="filtersActionWrapper">

      {% comment %} Validar por permiso {% endcomment %}
      <div id="selectWrapperSelectAgencia" class="wrapperSelectFilter">
          <label class="labelInput">Sucursal</label>
          <div class="containerInputAndOptions">
              <img class="iconDesplegar" src="{% static 'images/icons/arrowDown.png' %}" alt="">
              <input
                  type="text"
                  name="sucursal"
                  class="onlySelect input-select-custom"
                  id="inputSucursal"
                  autocomplete="off"
                  readonly=""
                  value="{{sucursalDefault.pseudonimo}}"
              />
              <ul class="list-select-custom options">
                  {% for sucursal in sucursales %}
                  <li data-value="{{sucursal.pseudonimo}}">{{sucursal.pseudonimo}}</li>
                  {% endfor %}
              </ul>
          </div>
      </div>

    </div>
    
  </form>   
  <div class="buttonsActionsWrapper">
    {% comment %} <button type="button" id="showModalFiltro" class="button-default-style" onclick="newModalIFiltro()">Exportar</button> {% endcomment %}
    <a href="{% url 'exportExcel' %}" id="buttonExport" class="add-button-default" >Exportar a Excel</a>
  </div>
</div>



<div class="informationWrapper">
  <a href="{% url 'users:list_customers'%}" id="buttonCleanFilter">Limpiar filtros</a>
  <div class="tableWrapper">
    <table class="informationTable">
      <thead>
          <tr>
              {% for key, value  in data.0.items %}
                <th>{{ value.verbose_name }}</th>
              {% endfor %}
            
          </tr>
      </thead>
      <tbody>
          {% for d in data %}
              <tr>
                {% for key, value  in d.items %}
                  <td>{{ value.data }}</td>
                {% endfor %}
              </tr>
          {% endfor %}
      </tbody>
    </table>
  </div>
</div> 

<div class="paginationWrapper">
  {% if data.has_previous %}
      <button class="buttonsPagesManage" id="previouPageButton" value="{{ data.previous_page_number }}">Anterior</button>
  {%else%}
      <button class="buttonsPagesManage" id="previouPageButton" value="1" disabled>Anterior</button>
  {% endif %}

  <span id="textPaginator">Página {{ data.number }} de {{ data.paginator.num_pages }}</span>

   {% if data.has_next %} 
      <button class="buttonsPagesManage" id="nextPageButton" value="{{ data.next_page_number }}">Siguiente</button>
   {%else%}
      <button class="buttonsPagesManage" id="nextPageButton" value="{{ data.paginator.num_pages }}" disabled>Siguiente</button>
    {% endif %} 
</div>

{% endblock content %}
{% block js %}
<script>
  var csrf_token = '{%csrf_token%}'
  var urlImportData = "{% url 'users:importClientes' %}"
  {% comment %} var sucursalesDisponibles = {{ sucursalesDisponiblesJSON|safe }}; {% endcomment %}
  var logoDisplayMore = "{% static 'images/icons/arrowDown.png' %}";
  var tipoSlug = "{{ tipo }}";
</script>



<script src="{% static 'modalStatic/doc/tingle/tingle.min.js' %}"></script>
<script src="{% static 'js/users/importDataCliente.js' %}"></script>
<script src="{% static 'js/vanilla_components/inputSelectOnly_v2.js.js' %}"></script>


{% endblock js %}

elanelsystem/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <title>Elanel SYS</title>
</head>
<body>
    <div class="wrapper">
        <img src="{% static 'images/circulo1.svg' %}" alt="" id = "top_left_circle">
        <img src="{% static 'images/circulo2.svg' %}" alt="" id = "bottom_left_circle">
        <div class="logo">
            <figure><img src="{% static 'images/logo_index.png' %}" alt=""></figure>
        </div>
        <div class="form_wrapper">
            <form method = "post">
                <h2>INICIAR SESION</h2>
                {% csrf_token %}
                {% comment %} {{form.as_p}} {% endcomment %}
                <input type="text" name="username" class="credenciales" maxlength="254" required="" id="id_username" placeholder = "Correo Electronico" autocomplete="off">
                <input type="password" name="password" class="credenciales" required="" id="id_password" placeholder = "Contraseña" autocomplete ="off">
                <input type="submit" value="Ingresar">
            </form>
        </div>
    </div>
</body>
</html>

elanelsystem/templates/mailPlantilla.html
<!DOCTYPE html>
<html lang="es">
    <body>
        <h1>WEPS</h1> 
    </body>
</html>

elanelsystem/templates/molde.html
{% load static %}
{% load util %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/molde.css' %}">
    <link rel="stylesheet" href="{% static 'css/root_base.css' %}">
    <link rel="shortcut icon" href="{% static 'images/icon_windown.png' %}">

    {% block css %}
    {% endblock css %}
    <title>ElanelSYS</title>
</head>
<body>
    <div class="wrapper">

        <aside class="menu" id="menu">
            <div class="tittleAsideWrapper">
                <div class="logoWrapper">
                    <img src="{% static 'images/icono.sinfondo_admin.png' %}" alt="">
                </div>
                <h3 class="tittleAside">Elanel Servicios SRL</h3>
            </div>
            <div class="aside-item-perfil">
                {% iniciales_de_nombre_usuario as iniciales %}
                    <div class="circleNombre">
                        {{iniciales}}
                    </div>
                    <div class="nombreUsuarioWrapper">
                    {% nombre_completo_usuario as nombre_completo %}
                    {% rango_usuario as rango %}
                        <h3>{{nombre_completo}}</h3>
                        <h5>{{rango}}</h5>
                    </div>  
            </div>
            
            <ul class="list">
                
                {% seccionesPorPermisos as secciones %}
                {% for seccion, data in secciones.items %}
                    <li>
                        <a href="{{data.url}}" id="{{seccion|lower}}">
                            <img src="{{data.image}}" alt="">
                            <p>{{data.tag_name}}</p> 
                        </a>
                    </li>
                {% endfor %}
                
                <li>
                    <a href="{% url 'users:configurarPerfil'%}" id="perfil">
                        <img src="{% static 'images/icons_sider/perfil.svg' %}" alt="">
                        <p>Perfil</p> 
                    </a>
                    <div class="check"></div>
                </li>

                <li>
                    <a data-logout href="{% url 'logout' %}" id="close_session">
                        <img src="{% static 'images/icons_sider/logout.svg' %}" alt="">
                        <p>Cerrar sesion</p> 
                    </a>
                    <div class="check"></div>
                </li>
            </ul>
        </aside>

        <div class="wrapper_content">
            {% block content %}
            {% endblock content %}
        </div>

    </div>
    
    <script src="{% static 'js/vanilla_components/menu.js' %}"></script>
    <script src="{% static 'js/auth/permGate.js' %}" defer></script>
    <script>
        document.addEventListener("DOMContentLoaded", () => {
            if (window.PERM_GATE) PERM_GATE.init();
        });
        document.querySelectorAll("[data-logout]").forEach(el => {
            el.addEventListener("click", () => {
                try { sessionStorage.removeItem("perm-cache-v1"); } catch(_) {}
                try { localStorage.setItem("perm-broadcast", "logout:" + Date.now()); } catch(_) {}
            });
        });
    </script>
    {% if not request.user.is_authenticated %}
    <script>
    try { sessionStorage.removeItem("perm-cache-v1"); } catch(_) {}
    try { localStorage.setItem("perm-broadcast", "logout:" + Date.now()); } catch(_) {}
    </script>
    <script>
    window.addEventListener("storage", (e) => {
    if (e.key === "perm-broadcast" && String(e.newValue || "").startsWith("logout:")) {
        try { sessionStorage.removeItem("perm-cache-v1"); } catch(_) {}
        if (window.PERM_GATE && typeof PERM_GATE.refresh === "function") {
        PERM_GATE.refresh().catch(() => {});
        }
    }
    });
    </script>
    {% endif %}
    {% block js %}
    {% endblock js %}

</body>
</html>

elanelsystem/templates/molde_v2.html
{% load static %}
{% load util %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/molde.css' %}">
    <link rel="stylesheet" href="{% static 'css/root_base_2.css' %}">
    <link rel="shortcut icon" href="{% static 'images/icons/diamong.png' %}">

    {% block css %}
    {% endblock css %}
    <title>ElanelSYS</title>
</head>
<body>
    <div class="wrapper">

        <aside class="menu active" id="menu">
            <div class="tittleAsideWrapper">
                <div class="logoWrapper">
                    <img src="{% static 'images/icons/logo.png' %}" alt="">
                </div>
                <h3 class="tittleAside">Elanel Servicios SRL</h3>
            </div>
            
            <ul class="list">
                <li class="aside-item perfil">
                {% iniciales_de_nombre_usuario as iniciales %}
                    <div class="circleNombre">
                        {{iniciales}}
                    </div>
                    <div class="nombreUsuarioWrapper">
                    {% nombre_completo_usuario as nombre_completo %}
                    {% rango_usuario as rango %}
                        <h3>{{nombre_completo}}</h3>
                        <h3>{{rango}}</h3>
                    </div>  

                </li>
                {% seccionesPorPermisos as secciones %}
                {% for seccion, data in secciones.items %}
                    <li>
                        <a href="{{data.url}}" id="{{seccion|lower}}">
                            <p>{{seccion}}</p> 
                        </a>
                        <div class="check"></div>
                    </li>
                {% endfor %}

                <li>
                    <a href="{% url 'users:configurarPerfil'%}" id="close_session">
                        <p>Configurar perfil</p> 
                    </a>
                    <div class="check"></div>
                </li>

                <li>
                    <a href="{% url 'logout' %}" id="close_session">
                        <img src="{% static 'images/icons/logout.png' %}" alt="">
                        <p>Cerrar sesion</p> 
                    </a>
                    <div class="check"></div>
                </li>
            </ul>
        </aside>

        <div class="wrapper_content">
            {% block content %}
            {% endblock content %}
        </div>

    </div>
    
    <script src="{% static 'js/vanilla_components/menu.js' %}"></script>

    {% block js %}
    {% endblock js %}

</body>
</html>

elanelsystem/templates/reportes.html
{% extends 'molde.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/panel_admin.css' %}">
<link href="{% static 'js/vanilla-calendar/build/vanilla-calendar.min.css' %}" rel="stylesheet">
<script src="{% static 'js/vanilla-calendar/build/vanilla-calendar.min.js' %}" defer></script>
<link rel="stylesheet" href="{% static 'css/modalWindows.css' %}">
<link rel="stylesheet" href="{% static 'css/root_base.css' %}">
{% endblock css %}

{% block content %}

    {% for reporte in tiposDeReportes %}
        <div class="wrapperSections">
            <div class ="tittleWrapper">
                <h4>{{ reporte|capfirst }}</h4>
            </div>
            <div class="buttonWrapper">
                {% comment %} <a id="expCannons" class="buttonMore"> {% endcomment %}
                <a href="{% url 'detalle_por_tipoDeDatos' reporte %}" class="buttonMore">
                    <div>
                        <h3>Ver</h3>
                        <img src="{% static 'images/icons/nextSinBackground.png' %}" alt="">
                    </div>
                </a>
            </div>
        
        </div>
    {% endfor %}
    
    <!-- MODAL DE FILTROS DEFAULT  -->
    <!-- Respetar estructura del modal-->
    {% comment %} <div class="modalFilterContainer">
        <div class="background"></div>
        <div class="windowModal">
            
            <button type="button" id="closeFormFilter">
                <img src="{% static 'images/icons/close.svg' %}" alt="">
            </button>

            <form method="POST" id="filterForm" class="filterForm">
                {% csrf_token %}
                <input type="hidden" name="typeReporte" value="Cannons">

                <div class="wrapperCalendario wrapperTypeFilter">
                    <h3 class="labelFilterElement">Filtrar por fecha</h3>
                    <div class="containerCalendario">
                        <input id="calendar-input" name="fecha" class="filterInput input-read-write-default" type="text" placeholder="Elija la fecha" readonly />
                        <div class="calendar" id="calendar"></div>
                    </div>
                </div>

                <div id="selectWrapperSelectTypePayments" class="wrapperTypeFilter">
                    <h3 class="labelFilterElement">Filtrar por tipo de pago</h3>
                    <div class="containerInputAndOptions">
                      <img class="iconDesplegar" src="{% static 'images/icons/arrowDown.png' %}" alt="">

                      <input type="text" name="tipo_pago" class = "input-select-custom multipleSelect" id ="tipoDePago" placeholder ="Elija el metodo de pago" autocomplete="off" readonly>
                      <ul class="list-select-custom options">
                            <li data-value="Efectivo">Efectivo</li>
                            <li data-value="Banco">Banco</li>
                            <li data-value="Mercado Pago">Mercado Pago</li>
                            <li data-value="Posnet">Posnet</li>
                            <li data-value="Transferencia">Transferencia</li>
                      </ul>
                    </div>
                </div>
                
                <div id="selectWrapperSelectAgency" class="wrapperTypeFilter">
                    <h3 class="labelFilterElement">Filtrar por sucursal</h3>
                    <div class="containerInputAndOptions">
                      <img class="iconDesplegar" src="{% static 'images/icons/arrowDown.png' %}" alt="">
                      <input type="text" name="agencia" class = "multipleSelect input-select-custom" id ="sucursalInput" value="{{user.sucursal.pseudonimo}}"placeholder ="Elija la sucursal" autocomplete="off" readonly>
                      <ul class="list-select-custom options">
                            <li data-value="Efectivo">Efectivo</li>
                            <li data-value="Banco">Banco</li>
                            <li data-value="Mercado Pago">Mercado Pago</li>
                            <li data-value="Posnet">Posnet</li>
                            <li data-value="Transferencia">Transferencia</li>
                      </ul>
                    </div>
                </div>

                <div id="selectWrapperSelectCobrador"class="wrapperTypeFilter">
                    <h3 class="labelFilterElement">Filtrar por cobrador</h3>
                    <div class="containerInputAndOptions">
                      <img class="iconDesplegar" src="{% static 'images/icons/arrowDown.png' %}" alt="">
                      <input type="text" name="cobrador" class = "multipleSelect input-select-custom" id ="cobradorInput" value="" placeholder ="Elija el cobrador" autocomplete="off" readonly>
                      <ul class="list-select-custom options">
                            {% for cobrador in cobradores %}
                                <li>{{cobrador.nombre}}</li>
                            {% endfor %}
                            <li data-value="Efectivo">Efectivo</li>
                            <li data-value="Banco">Banco</li>
                            <li data-value="Mercado Pago">Mercado Pago</li>
                            <li data-value="Posnet">Posnet</li>
                            <li data-value="Transferencia">Transferencia</li>
                      </ul>
                    </div>
                </div>  

                <div id="wrapperRadioEgresoIngreso" class="wrapperTypeFilter">
                    <h3 class="labelFilterElement">Filtrar por:</h3>
                    <div class="selectEgreso_Ingreso inputsRadiosContainer">
                        <input type="radio" name="tipo_mov" id="ingreso" value="Ingreso">
                        <label for="ingreso">Ingreso</label>
        
                        <input type="radio" name="tipo_mov" id="egreso" value="Egreso">
                        <label for="egreso">Egreso</label>
                    </div>
                </div>                  
            </form>

            <button id="submitFilter" class="add-button-default" form="filterForm" type="submit">Filtrar</button>
        </div>
    </div> {% endcomment %}


{% endblock content %}
{% block js %}
{% comment %} <script src="{% static 'js/vanilla_components/inputsSelectsMultipleCustoms.js.js' %}"></script> {% endcomment %}
{% comment %} <script src="{% static 'js/inputsRadiosManage.js' %}"></script> {% endcomment %}
{% comment %} <script src="{% static 'js/manageModalFilter.js' %}"></script> {% endcomment %}
{% comment %} <script src="{% static 'js/vanilla-calendar/multipleCalendarManage.js' %}" defer></script> {% endcomment %}

{% endblock js %}