elanelsystem/sales/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from configuracion import views
from .views import *
from .utils import exportar_excel  # Importa la función de exportación
from .views import GraficosDashboard,DashboardColaboradores
from .views import ventas_analytics_api, exportar_ventas_excel, exportar_pagos_cannon_excel
from .views import graficos
app_name="sales"

urlpatterns = [

    path("resumen/",Resumen.as_view(),name="resumen"),

    #region URLs Ventas ----------------------------------
    path("ventas/importar/",importVentas,name="importVentas"),
    path("ventas/cliente/<int:pk>/crear_venta/",CrearVenta.as_view(),name="create_sale"),
    path("ventas/get_vendedores_supervisores/",requestVendedores_Supervisores,name="requestVendedores_Supervisores"),
    path("ventas/detalles", VentasDetalles.as_view(),name="detallesVentas"),
    path("ventas/detalle_venta/<int:pk>/",DetailSale.as_view(),name="detail_sale"),

    path("ventas/detalle_venta/<int:pk>/eliminar_venta/",eliminarVenta,name="delete_sale"),
    path("ventas/detalle_venta/descuento_cuota/",aplicarDescuentoCuota,name="descCuota"),
    path("ventas/detalle_venta/get_specific_cuota/",getUnaCuotaDeUnaVenta,name="getCuota"),
    path("ventas/detalle_venta/pay_cuota/",pagarCuota,name="payCuota"),
    # path("ventas/detalle_venta/anular_cuota/",anularCuota,name="anularCuota"),

    path("ventas/detalle_venta/<int:pk>/dar_baja/",darBaja,name="darBaja"),
    path("ventas/<int:pk>/adjudicacion/sorteo/",CreateAdjudicacion.as_view(),name="adjSorteo"),
    path("ventas/<int:pk>/adjudicacion/negociacion/",CreateAdjudicacion.as_view(),name="adjNegociacion"),
    path("ventas/<int:pk>/cambiopack",ChangePack.as_view(),name="cambioPack"),
    path("ventas/<int:pk>/cambiotitularidad",ChangeTitularidad.as_view(),name="changeTitu"),
    path("ventas/ventas_suspendidas",PanelVentasSuspendidas.as_view(),name="ventasSuspendidas"),
    path("ventas/simulador_plan_recupero/<int:pk>/",SimuladorPlanRecupero.as_view(),name="simuladorPlanrecupero"),
    path("ventas/crear_plan_recupero/<int:pk>/",PlanRecupero.as_view(),name="planRecupero"),
    
    path("ventas/detalle_venta/solcitud_anulacion_cuota/",solicitudBajaCuota,name="solicitudAnulacionCuota"),
    path('ventas/detalle_venta/autorizar-baja/<int:ventaID>/<str:cuota>/', darAutorizacionBajaCuota, name='autorizar_baja_cuota'),
    path('ventas/detalle_venta/pagina_confirmacion_baja_cuota/', pagina_confirmacion, name='pagina_confirmacion_baja_cuota'),
    path('ventas/detalle_venta/confirma-baja-cuota/', darBajaCuota, name='darBajaCuota'),

    path('ventas/comisionables/',VentasComisionables.as_view(),name='ventas_comisionables'),
    # endpoint AJAX para toggle
    path('ventas/comisionable-toggle/',toggle_comisionable,name='toggle_comisionable'),
    # endpoint para el dashboard de gráficos
    path('graficos/', GraficosDashboard.as_view(), name='graficos'),
    path('graficos/cannon/', graficos_pagos_cannon, name='graficos_cannon'),
    path('dashboard/colaboradores/', DashboardColaboradores.as_view(), name='dashboard_colaboradores'),
    path('api/autocomplete-colaborador/', autocomplete_colaborador, name='autocomplete_colaborador'),
    path('api/ventas-colaborador/', ventas_colaborador, name='ventas_colaborador'),
    path('api/ventas-analytics/', ventas_analytics_api, name='ventas_analytics_api'),
    path('api/pagos-cannon-analytics/', pagos_cannon_analytics_api, name='pagos_cannon_analytics_api'),
    path('api/exportar-ventas-excel/', exportar_ventas_excel, name='exportar_ventas_excel'),
    path('api/exportar-pagos-cannon-excel/', exportar_pagos_cannon_excel, name='exportar_pagos_cannon_excel'),
    #endregion ----------------------------------------------------------

    #region URLs Caja -----------------------------------------------------
    path("ventas/caja/",Caja.as_view(),name="caja"),
    path("arqueo/", CierreCaja.as_view(), name="arqueo"),
    path("arqueo/old/", OldArqueosView.as_view(), name="oldArqueos"),
    path("arqueo/saldo/", ArqueoSaldoAPI.as_view(), name="arqueoSaldo"),

    path("ventas/movs_pagos/", movs_pagos_list_api, name="movs_pagos_list"),
    path("ventas/movs_pagos/<str:kind>/<int:pk>/", movs_pagos_detail_api, name="movs_pagos_detail"),
    #endregion -----------------------------------------------------------
    
    #region URLs PDFs ------------------------------------------------------
    path("ventas/pdf/baja/<int:pk>",viewsPDFBaja,name="bajaPDF"),
    path("ventas/pdf/titularidad/<int:pk>/<int:idCambio>",viewPDFTitularidad,name="tituPDF"),
    path("ventas/pdf/arqueo/<int:pk>/",viewPDFArqueo,name="arqueoPDF"),
    path("ventas/pdf/informe/", viewsPDFInforme, name="ventas_pdf_informe"),
    path("ventas/excel/informe/", viewsExcelInforme, name="ventas_excel_informe"),
    # path('ventas/detalle_venta/recibo/pago/<int:pk>/', viewPDFReciboCuota, name='getReciboCuota'),
    #     path(
    #     "ventas/detalle_venta/recibo-json/pago/<int:pk>/",
    #     recibo_pago_json,
    #     name="recibo-pago-json"
    # ),
    path('ventas/detalle_venta/recibo-preview/<int:pk>/', recibo_preview, name='recibo-preview'),
    #endregion ---------------------------------------------------------
        
    #region URLs PostVentas --------------------------------------------
    path("ventas/postventas/", PostVenta.as_view(), name="postVentaList"),
    path("ventas/auditorias/api/", auditorias_api, name="auditorias_api"),
    path("ventas/auditorias/crear/", crear_auditoria, name="crear_auditoria"),
    path('ventas/postventas/informe/', viewsPDFInformePostVenta, name='postVentaPDF'),
    #endregion ---------------------------------------------------------
    
    #region URLs Specifics Functions ------------------------------------------------------------
    # path('ventas/detalles/', requestDetallesVentas, name='requestDetallesVentas'),
    # path('ventas/request_ventas/', requestVentasAuditoria, name='requestVentasAuditorias'),

    path('requestmovs/', requestMovimientos, name='rmovs'),
    path('create_new_mov/', createNewMov, name='create_new_mov'),
    #endregion --------------------------------------------------------------------------------

    path("api/cotizaciones/dolar/", cotizaciones_dolar, name="cotizaciones_dolar"),
]

elanelsystem/users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *
 
app_name="users"

urlpatterns = [
    path("usuario/api/me/", me, name="me"),

    path("usuario/crear_usuario/",CrearUsuario.as_view(),name="create_user"),
    path("usuario/search/",requestUsuarios2,name="searchUsers"),

    path("usuario/lista_usuarios/",ListaUsers.as_view(),name="list_users"),
    path("cliente/importUsuarios/",importar_usuarios,name="importUsuarios"),
    path("usuario/aplicar_descuento/",realizarDescuento,name="realizarDescuento"),
    path("usuario/detalleusuario/<int:pk>/",DetailUser.as_view(),name="detailUser"),
    path("cliente/lista_clientes/",ListaClientes.as_view(),name="list_customers"),
    path("cliente/importClientes/",importar_clientes,name="importClientes"),
    path("usuario/administracion/requestusuarios/",requestUsuarios,name="requestUsuarios"),
    path("cliente/crear_cliente/",CrearCliente.as_view(),name="create_customer"),
    path("cliente/<int:pk>/operaciones/",CuentaUser.as_view(),name="cuentaUser"),
    path("usuario/administracion/",PanelAdmin.as_view(),name="panelAdmin"),
    path("usuario/administracion/permisos/",PanelPermisos.as_view(),name="panelPermisos"),
    path("usuario/configurar_perfil/",ConfiguracionPerfil.as_view(),name="configurarPerfil"),


    #region Sucursal CRUD - - - - - - - -
    path("usuario/administracion/sucursales/",PanelSucursales.as_view(),name="panelSucursales"),
    path("usuario/administracion/sucursales/add",addSucursal,name="addSucursal"),
    path("usuario/administracion/sucursales/remove",removeSucursal,name="removeSucursal"),
    path("usuario/administracion/sucursales/update",updateSucursal,name="updateSucursal"),
    #endregion - - - - - - - - - - - - - - 

    #region Cuenta de cobros CRUD - - - - - - - -
    path("usuario/administracion/cuentas_cobros/",PanelCuentaCobro.as_view(),name="panelCuentaDeCobro"),
    path("usuario/administracion/cuentas_cobros/add",addCuenta,name="addCuenta"),
    path("usuario/administracion/cuentas_cobros/remove",removeCuenta,name="removeCuenta"),
    #endregion - - - - - - - - - - - - - - 

    #region Permisos - - - - - - -  - - - - - - - - - - - -
    path("usuario/administracion/requestpermisos/",requestPermisosDeGrupo,name="requestPermisos"),
    path("usuario/administracion/updatepermisos/",updatePermisosAGrupo,name="updatePermisos"),
    path("usuario/administracion/createnewgroup/",createNewGroup,name="newGroup"),
    path("usuario/administracion/deletenewgroup/",deleteGrupo,name="deleteGroup"),
    path("usuario/administracion/requestkey/",requestKey,name="requestKey"),
    #endregion  - - - - - - - - - - - - - - - - - - - - - - - -

    path("usuario/pdf/ficha_creacion/<int:pk>",viewsPDFNewUser,name="newUserPDF"),

]

elanelsystem/sales/templates/caja.html
{% extends 'molde.html' %}
{% load static %}
{% load humanize %}
{% load i18n %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/caja.css' %}">
<link rel="stylesheet" href="{% static 'css/root_base.css' %}">
<link rel="stylesheet" href="{% static 'modalStatic/doc/tingle/tingle.min.css' %}">

<link href="{% static 'js/vanilla-calendar-pro/styles/index.css' %}" rel="stylesheet">
<script src="{% static 'js/vanilla-calendar-pro/index.js' %}" defer></script>

<link rel="stylesheet" href="{% static 'css/vanilla_table.css' %}" />

{% endblock css %}

{% block content %}
    <div class="header_section">
        <div class="titleHeaderWrapper">
            <img src="{% static 'images/icons_sider/caja.svg' %}" alt="">
            <h1 class="titleHeader">CAJA</h1>
        </div>
          <a id="btn_generar_pdf"
            class="button-default-style"
            href="{% url 'sales:ventas_pdf_informe' %}"
            target="_blank">
            Generar PDF
        </a>

        <a id="btn_generar_excel"
            class="button-default-style"
            href="{% url 'sales:ventas_excel_informe' %}"
            target="_blank">
            Generar Excel
        </a>
        <a class="button-default-style" href="{% url 'sales:oldArqueos' %}" id="oldArqueos"> Ver arqueos anteriores</a>

        <a class="add-button-default" href="{% url 'sales:arqueo' %}">Cerrar caja</a>

    </div>

    <!-- INFORMACION DE CAJA -->
    <div class ="caja">
        <div class="movimientos">
            <div id="caja_table" class="vt-sticky"></div>
        </div>

        <div class="resumWrapper">
            <div class="resumTableWrapper">
                <table class="resum_table">
                    <thead>
                        <tr>
                            <th>Tipo de caja</th>
                            {% comment %} <th>Ingreso</th>
                            <th>Egreso</th> {% endcomment %}
                            <th>Saldo</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
            {% comment %} <div class="wrapperButtonInforme">
            </div> {% endcomment %}

        </div>
    </div>

{% endblock content %}

{% block js %}
<script>
    var campaniasDisponibles = {{campaniasDisponibles | safe}};
    var CSRF_TOKEN = '{% csrf_token %}';
    var imgNext = "{% static 'images/icons/arrowDown.png' %}";
    var campanias = {{campanias | safe}};
    var agencias = {{agencias_permitidas | safe}};
    var cuentas_de_cobro = {{cuentas_de_cobro | safe}};
    var metodos_de_pago = {{metodos_de_pago | safe}};
</script>


<!-- Scripts bases: manejo de multipleSelects, OnlySelect, Controlar el modal de filter, el calendario de fechas, y el manejador de los inputs radios-->
<script src="{% static 'modalStatic/doc/tingle/tingle.min.js' %}"></script>
<script src="{% static 'js/vanilla-calendar-pro/multipleCalendarManage.js' %}" defer></script>
<script src="{% static 'js/vanilla-calendar-pro/singleCalendarWithTime.js' %}" defer></script>

<script src="{% static 'js/vanilla_components/inputSelectOnly.js' %}"></script>
{% comment %} <script src="{% static 'js/vanilla_components/inputsMultipleSelect_v2.js' %}"></script> {% endcomment %}
<script src="{% static 'js/vanilla_components/z_index_orders_selects.js' %}"></script>

<script src="{% static 'js/sales/createNewMov.js' %}"></script>
<script type="module" src="{% static 'js/users/caja_table.js' %}"></script>

{% endblock js %}

elanelsystem/sales/templates/changeTitularidad.html
{% extends 'molde.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/selectNewCustomerForChange.css' %}">
<link rel="stylesheet" href="{% static 'css/root_base.css' %}">
{% endblock css %}

{% block content %}
<div class="filters">
  <h3>Elija el cliente con el que desea reemplazarlo</h3>
    <div>
      <input 
      type="text"
      class = "customer input-read-write-default"
      id="customer_search">
      <img src="{% static 'images/icons/search.svg' %}" alt="">
    </div>

</div>
<form method="POST" id="formSelectCustomer" class="valuesWrapper">
  <input type="hidden" name="customer" required id="customer_input">
  {% csrf_token %}
  <table class="information">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>DNI</th>
            <th>Teléfono</th>
            <th>Localidad</th>
            <th>Provincia</th>
        </tr>
    </thead>
    <tbody class="values">
          {% for customer in customers %}
          <tr class="customer_item">
              <td id="name"><input id="select_client" class="checkbox_select_client" type="checkbox" name="select_client">{{customer.nombre}}</td>
              <td id="dni">{{customer.dni}}</td>
              <td id="tel">{{customer.tel}}</td>
              <td id="loc">{{customer.loc}}</td>
              <td id="prov">{{customer.prov}}</td>
          </tr>
          {% endfor %} 
    </tbody>
  </table>
</form>
<div class="buttonsWrapper">
  <div>
    <button id="yesConfirm" disabled class="add-button-default" type="button" form="formSelectCustomer">Confirmar</button>
    <a class ="delete-button-default" href="{% url 'sales:detail_sale' object.id %}">Cancelar</a>
  </div>
</div>

{% endblock content %}
{% block js %}
<script>

  var urlGetCustomers = "{% url 'users:list_customers' %}";
  var urlGetCustomers = "{% url 'sales:changeTitu' object.pk%}";

  function actualizarResultados(resultados, contenedor) {
    // Limpia el contenedor de los datos
    contenedor.innerHTML = "";

    
    for (let i = 0; i < resultados.length; i++) {
      let element = resultados[i];
      let cliente = `
      <tr class="customer_item">
        <td id="name"><input class="checkbox_select_client" type="checkbox" name="select_client">${element.nombre}</td>
        <td id="dni">${element.dni}</td>
        <td id="tel">${element.tel}</td>
        <td id="loc">${element.loc}</td>
        <td id="prov">${element.prov}</td>
      </tr>
      `;
      contenedor.insertAdjacentHTML("beforeend", cliente);
    }
    
    seleccionarNuevoCliente();
  }
</script>
<script src="{% static 'js/users/selectCustomerChangeTitularidad.js' %}"></script>
{% endblock js %}

elanelsystem/sales/templates/confirmacion_baja_cuota.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmación de Autorización</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            padding: 50px;
            background-color: #f8f9fa;
        }
        .container {
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
            max-width: 500px;
            margin: auto;
        }
        h1 {
            color: #28a745;
        }
        p {
            font-size: 18px;
            color: #333;
        }
        .button {
            display: inline-block;
            padding: 10px 20px;
            margin-top: 20px;
            background-color: #007bff;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            font-size: 16px;
        }
        .button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>¡Autorización Exitosa! ✅</h1>
        <p>La cancelación del pago de la cuota ha sido autorizada correctamente.</p>
        <p>Recuerda notificar al personal que ha solcitado la baja</p>
        <p>Ya puedes cerrar esta pestaña.</p>
    </div>
</body>
</html>

elanelsystem/sales/templates/crearclienteycambiar.html
{% extends 'molde.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/create_customer.css' %}">
{% endblock css %}
    
{% block content %}
    <div class="wrapper_tittle">
        <h1>NUEVO CLIENTE</h1>
    </div>
    <form method="post" id="form_create_customer" autocomplete="off">
        {% csrf_token %}
        {% for inp in form%} 
            <div class="inputWrapper" id="{{inp.auto_id}}w">
                <label for="">{{inp.label|truncatechars:13}}</label>
                {{inp}} 
            </div>
        {%endfor%}
    </form>
    <div class="wrapperButtons">
        <input type="submit" value="Guardar y cambiar" form="form_create_customer" id="save_customer">
        <a id ="cancelar" href="{% url 'sales:changeTitu' object.pk %}"> Cancelar </a>
    </div>
    


{% endblock content %}

elanelsystem/sales/templates/email_autorizacion_baja_cuota.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Autorización de Cancelación</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f7f6;
            padding: 20px;
            margin: 0;
            color: #555;
        }
        .container {
            background-color: #ffffff;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0px 10px 15px rgba(0, 0, 0, 0.1);
            max-width: 600px;
            margin: auto;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #007bff;
            font-size: 24px;
            margin: 0;
        }
        .header h2 {
            color: #28a745;
            font-size: 20px;
            margin-top: 5px;
        }
        .header h3 {
            color: #000;
            font-size: 20px;
            margin-top: 5px;
        }
        .content {
            font-size: 16px;
            line-height: 1.5;
            margin-bottom: 30px;
        }
        .content p {
            margin-bottom: 20px;
        }
        .button {
            display: inline-block;
            background-color: #28a745;
            color: white;
            padding: 12px 25px;
            text-decoration: none;
            font-size: 18px;
            border-radius: 5px;
            text-align: center;
            width: 100%;
            max-width: 250px;
            margin: auto;
            transition: background-color 0.3s ease;
            color: #fff!important;
        }
        .button:hover {
            background-color: #218838;
        }
        .footer {
            text-align: center;
            font-size: 14px;
            color: #777;
        }
        .footer a {
            color: #007bff;
            text-decoration: none;
        }
        .footer a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Autorización de Cancelación</h1>
            <h2>Venta N° {{ venta }}</h2>
            <h3>{{ cuota }}</h3>
        </div>

        <div class="content">
            <p>Estimado/a,</p>
            <p>Se ha solicitado la cancelación de la cuota indicada en el sistema. Para continuar con el proceso, por favor autorice la cancelación haciendo clic en el siguiente botón:</p>
            
            <a href="{{ url_autorizar }}" class="button" target="_blank">Autorizar Cancelación</a>
        </div>

        {% comment %} <div class="footer">
            <p>Si no solicitó esta cancelación, por favor ignore este mensaje.</p>
        </div> {% endcomment %}
    </div>
</body>
</html>

elanelsystem/sales/templates/listaDeArqueos.html
{% extends 'molde.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/root_base.css' %}">
<link rel="stylesheet" href="{% static 'css/vanilla_table.css' %}">
<link rel="stylesheet" href="{% static 'modalStatic/doc/tingle/tingle.min.css' %}">
<link rel="stylesheet" href="{% static 'css/historialArqueos.css' %}">

<style>
  .vt-table tbody tr { cursor: pointer; }
</style>
{% endblock css %}

{% block content %}
<div class="header_section">
    <div class="titleHeaderWrapper">
        <img src="{% static 'images/icons_sider/caja.svg' %}" alt="">
        <h1 class="titleHeader">HISTORIAL DE ARQUEOS</h1>
    </div>

    {% comment %} <div class="buttons">
        <a href="{% url 'sales:oldArqueos' %}" id="oldArqueos"> Ver arqueos anteriores</a>
        <button id="confirmArqueoCaja" type="button" form="formArqueoCaja">Confirmar cierre</button>   
    </div> {% endcomment %}
</div>

<div class="informationWrapper">
  <div id="arqueos_table" class="vt-sticky"></div>
</div>
{% endblock content %}

{% block js %}
<script>
  // urls para el fetch y el PDF
  var urlOldArqueos = "{% url 'sales:oldArqueos' %}";
  var urlPDFBase = "{% url 'sales:arqueoPDF' 0 %}";
  var imgNext = "{% static 'images/icons/arrowDown.png' %}";

  // sucursales para el select del filtro
  var sucursalesDisponibles = [
    {% for s in sucursales %}
      { id: {{ s.id }}, pseudonimo: "{{ s.pseudonimo|escapejs }}" },
    {% endfor %}
  ];
</script>

<script src="{% static 'modalStatic/doc/tingle/tingle.min.js' %}"></script>

<!-- tu select custom (el que ya usás en otras pantallas) -->
<script src="{% static 'js/vanilla_components/inputSelectOnly.js' %}"></script>
<script src="{% static 'js/vanilla_components/z_index_orders_selects.js' %}"></script>

<!-- tabla -->
<script type="module" src="{% static 'js/sales/arqueos_table.js' %}"></script>
{% endblock js %}

elanelsystem/sales/templates/panel_ventas_suspendidas.html
{% extends 'molde.html' %}
{% load static %}
{% load humanize %}
{% load i18n %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/panelVentasSuspendidas.css' %}">
<link rel="stylesheet" href="{% static 'css/root_base.css' %}">
{% endblock css %}

{% block content %}
<form class="filters" method="POST" id="form_filters_venta">
    {% csrf_token %}
    <h2>Nro de Venta</h2>
    <div class="searchFilter">
        <input type="text" name ="nro_operacion" class = "customer input-read-write-default" id="nro_ordenInput">
        <img src="{% static 'images/icons/search.svg' %}" alt="">
    </div>
    <button type="button" disabled id="submitFormVenta" class="add-button-default"> Buscar </button>
</form>

<div class="accountWrapper">

    <div class="operations">
        <div class="operationsWrapper">
            <ul class="operationsList">
                <div class="wrapperMessage">
                    <h2 class="messageInfoVacio">Coloque el numero de venta para filtrar la venta</h2>
                </div>
            </ul>       
        </div>
    </div> 
    

</div>

{% endblock content %}

{% block js %}

{% endblock js %}

elanelsystem/sales/templates/pdfForBaja.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Baja contrato N°{{nroContrato}}</title>

</head>
<body>
    <img src="{% static 'images/logoElanelPDF.png' %}" alt="">
    <div id ="imageLogo">
    </div>
    <div id="subtittle">
        <h2>Solicitud de baja</h2>
        <h2>{{agencia}}</h2>
    </div>
    <div id ="detalle">
        <h2>Numero de contraro: <strong>{{nroContrato}}</strong></h2>
        <h2>Cliente: <strong>{{cliente}}</strong></h2>
        <h2>Domicilio: <strong>{{domicilio}}</strong></h2>
        <h2>Localidad: <strong>{{localidad}}</strong></h2>
        <h2>Producto: <strong>{{producto}}</strong></h2>
        <h2>Pack: <strong>{{pack}}</strong></h2>
        <h2>Cantidad de cuotas pagas: <strong>{{cantCuotasPagadas}}</strong></h2>
        <h2>Cantidad de cuotas emitidas: <strong>{{cuotas}}</strong></h2>
        <h2>Dinero a devolver: <strong>{{dineroDevolver}}</strong></h2>
        <h2>Motivo de la baja: <strong>{{motivo}}</strong></h2>
        <h2>Observacion: <strong>{{observacion}}</strong></h2>
        <h2>Fecha de la baja: <strong>{{fecha}}</strong></h2>
    </div>
    <div id="contrato">
        <p>Por la presente solicito la baja del contrato suscripto dejando constancia  que mi voluntad resolutiva importa la extinción  de la relación contractual habida con Elanel Servicios y Soluciones, decisión que ha sido adoptada luego de ser debidamente informado y con pleno conocimiento de las consecuencias de la misma, conforme Art. 4 de la ley 24.240; no teniendo más nada que reclamar en ningún concepto.</p>
    </div>
    <div id="firmas">
        <div>
            <p>_______________________________</p>
            <h6><strong>Firma de conformidad</strong></h6>
        </div>
        <div>
            <p>_______________________________</p>
            <h6><strong>Aclaración de la Firma y DNI</strong></h6>
        </div>
        
    </div>
</body>
</html>



elanelsystem/sales/templates/pdfForInforme.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Informe</title>
</head>
<body>
  <h1 class="tittleOfSections">Detalle de cierre de caja</h1>

  {% if data %}
  <table>
    <tr>
      {% for clave in data.0.keys %}
        <th><p>{{ clave }}</p></th>
      {% endfor %}
    </tr>
    {% for dicc in data %}
      <tr>
        {% for k,v in dicc.items %}
          <td><p>{{ v }}</p></td>
        {% endfor %}
      </tr>
    {% endfor %}
  </table>
  {% else %}
    <p style="font-size:14px;opacity:.75;">Sin resultados.</p>
  {% endif %}

  <h1 class="tittleOfSections">Resúmen de dinero según métodos de pagos</h1>
  <div class="resumTableWrapper">
    <table class="resum_table">
      <thead>
        <tr>
          <th>Tipo de caja</th>
          <th>Saldo</th>
        </tr>
      </thead>
      <tbody>
        {% for metodo in metodosPagosResumen %}
          <tr class="{{ metodo.name_clean }}">
            <td>{{ metodo.verbose_name }}</td>
            <td>{{ metodo.neto|default:metodo.money }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</body>
</html>