elanelsystem/liquidacion/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *
 
app_name="liquidacion"

urlpatterns = [
    path("ventas/liquidaciones/panel/", LiquidacionesPanel.as_view(),name="liquidacionesPanel"),
    path("ventas/liquidaciones/comisiones/", LiquidacionesComisiones.as_view(),name="liquidacionesComisiones"),
    path("ventas/liquidaciones/requestColaboradores/", requestColaboradoresWithComisiones,name="requestColaboradoresWithComisiones"),
    path('ventas/liquidaciones/comisiones/nuevo_ajuste/', crearAjusteComision, name='crearAjusteComision'),
    # path("ventas/liquidaciones/new_ausencia_tardanza/", newAusenciaTardanza,name="newAusenciaTardanza"),
    path("ventas/liquidaciones/requestColaboradores_tardanzasAusencias/", requestColaboradores_TardanzasAusencias,name="requestColaboradores_TardanzasAusencias"),
    path("ventas/liquidaciones/ranking/", LiquidacionesRanking.as_view(),name="liquidacionesRanking"),
    path("ventas/liquidaciones/ausencias_tardanzas/", LiquidacionesAusenciaYTardanzas.as_view(),name="liquidacionesAusenciaYTardanzas"),    
    path("ventas/liquidaciones/pdf/pre_liquidacion/", preViewPDFLiquidacion, name="preViewPDFLiquidacion"),
    path('ventas/liquidaciones/pdf/liquidacion/<int:id>/', viewPDFLiquidacion, name='viewPDFLiquidacion'),
    path('ventas/liquidaciones/detalles/<slug:tipo_slug>/', DetallesComisionesView.as_view(), name='detallesComisionesView'),
    path("ventas/liquidaciones/pdf/recibo_liquidacion_especifico/", reciboPDFLiquidacionEspecifico, name="reciboPDFLiquidacionEspecifico"),


    path("ventas/liquidaciones/historial/", HistorialLiquidaciones.as_view(), name="historialLiquidaciones"),
    path("export-comision-excel/", export_excel_detalle_comisionado, name="export_comision_excel"),
]

elanelsystem/sales/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from configuracion import views
from .views import *
from .utils import exportar_excel  # Importa la función de exportación
from .views import GraficosDashboard,DashboardColaboradores
from .views import ventas_analytics_api, exportar_ventas_excel, exportar_pagos_cannon_excel
from .views import graficos
app_name="sales"

urlpatterns = [

    path("resumen/",Resumen.as_view(),name="resumen"),

    #region URLs Ventas ----------------------------------
    path("ventas/importar/",importVentas,name="importVentas"),
    path("ventas/cliente/<int:pk>/crear_venta/",CrearVenta.as_view(),name="create_sale"),
    path("ventas/get_vendedores_supervisores/",requestVendedores_Supervisores,name="requestVendedores_Supervisores"),
    path("ventas/detalles", VentasDetalles.as_view(),name="detallesVentas"),
    path("ventas/detalle_venta/<int:pk>/",DetailSale.as_view(),name="detail_sale"),

    path("ventas/detalle_venta/<int:pk>/eliminar_venta/",eliminarVenta,name="delete_sale"),
    path("ventas/detalle_venta/descuento_cuota/",aplicarDescuentoCuota,name="descCuota"),
    path("ventas/detalle_venta/get_specific_cuota/",getUnaCuotaDeUnaVenta,name="getCuota"),
    path("ventas/detalle_venta/pay_cuota/",pagarCuota,name="payCuota"),
    # path("ventas/detalle_venta/anular_cuota/",anularCuota,name="anularCuota"),

    path("ventas/detalle_venta/<int:pk>/dar_baja/",darBaja,name="darBaja"),
    path("ventas/<int:pk>/adjudicacion/sorteo/",CreateAdjudicacion.as_view(),name="adjSorteo"),
    path("ventas/<int:pk>/adjudicacion/negociacion/",CreateAdjudicacion.as_view(),name="adjNegociacion"),
    path("ventas/<int:pk>/cambiopack",ChangePack.as_view(),name="cambioPack"),
    path("ventas/<int:pk>/cambiotitularidad",ChangeTitularidad.as_view(),name="changeTitu"),
    path("ventas/ventas_suspendidas",PanelVentasSuspendidas.as_view(),name="ventasSuspendidas"),
    path("ventas/simulador_plan_recupero/<int:pk>/",SimuladorPlanRecupero.as_view(),name="simuladorPlanrecupero"),
    path("ventas/crear_plan_recupero/<int:pk>/",PlanRecupero.as_view(),name="planRecupero"),
    
    path("ventas/detalle_venta/solcitud_anulacion_cuota/",solicitudBajaCuota,name="solicitudAnulacionCuota"),
    path('ventas/detalle_venta/autorizar-baja/<int:ventaID>/<str:cuota>/', darAutorizacionBajaCuota, name='autorizar_baja_cuota'),
    path('ventas/detalle_venta/pagina_confirmacion_baja_cuota/', pagina_confirmacion, name='pagina_confirmacion_baja_cuota'),
    path('ventas/detalle_venta/confirma-baja-cuota/', darBajaCuota, name='darBajaCuota'),

    path('ventas/comisionables/',VentasComisionables.as_view(),name='ventas_comisionables'),
    # endpoint AJAX para toggle
    path('ventas/comisionable-toggle/',toggle_comisionable,name='toggle_comisionable'),
    # endpoint para el dashboard de gráficos
    path('graficos/', GraficosDashboard.as_view(), name='graficos'),
    path('graficos/cannon/', graficos_pagos_cannon, name='graficos_cannon'),
    path('dashboard/colaboradores/', DashboardColaboradores.as_view(), name='dashboard_colaboradores'),
    path('api/autocomplete-colaborador/', autocomplete_colaborador, name='autocomplete_colaborador'),
    path('api/ventas-colaborador/', ventas_colaborador, name='ventas_colaborador'),
    path('api/ventas-analytics/', ventas_analytics_api, name='ventas_analytics_api'),
    path('api/pagos-cannon-analytics/', pagos_cannon_analytics_api, name='pagos_cannon_analytics_api'),
    path('api/exportar-ventas-excel/', exportar_ventas_excel, name='exportar_ventas_excel'),
    path('api/exportar-pagos-cannon-excel/', exportar_pagos_cannon_excel, name='exportar_pagos_cannon_excel'),
    #endregion ----------------------------------------------------------

    #region URLs Caja -----------------------------------------------------
    path("ventas/caja/",Caja.as_view(),name="caja"),
    path("arqueo/", CierreCaja.as_view(), name="arqueo"),
    path("arqueo/old/", OldArqueosView.as_view(), name="oldArqueos"),
    path("arqueo/saldo/", ArqueoSaldoAPI.as_view(), name="arqueoSaldo"),

    path("ventas/movs_pagos/", movs_pagos_list_api, name="movs_pagos_list"),
    path("ventas/movs_pagos/<str:kind>/<int:pk>/", movs_pagos_detail_api, name="movs_pagos_detail"),
    #endregion -----------------------------------------------------------
    
    #region URLs PDFs ------------------------------------------------------
    path("ventas/pdf/baja/<int:pk>",viewsPDFBaja,name="bajaPDF"),
    path("ventas/pdf/titularidad/<int:pk>/<int:idCambio>",viewPDFTitularidad,name="tituPDF"),
    path("ventas/pdf/arqueo/<int:pk>/",viewPDFArqueo,name="arqueoPDF"),
    path("ventas/pdf/informe/", viewsPDFInforme, name="ventas_pdf_informe"),
    path("ventas/excel/informe/", viewsExcelInforme, name="ventas_excel_informe"),
    # path('ventas/detalle_venta/recibo/pago/<int:pk>/', viewPDFReciboCuota, name='getReciboCuota'),
    #     path(
    #     "ventas/detalle_venta/recibo-json/pago/<int:pk>/",
    #     recibo_pago_json,
    #     name="recibo-pago-json"
    # ),
    path('ventas/detalle_venta/recibo-preview/<int:pk>/', recibo_preview, name='recibo-preview'),
    #endregion ---------------------------------------------------------
        
    #region URLs PostVentas --------------------------------------------
    path("ventas/postventas/", PostVenta.as_view(), name="postVentaList"),
    path("ventas/auditorias/api/", auditorias_api, name="auditorias_api"),
    path("ventas/auditorias/crear/", crear_auditoria, name="crear_auditoria"),
    path('ventas/postventas/informe/', viewsPDFInformePostVenta, name='postVentaPDF'),
    #endregion ---------------------------------------------------------
    
    #region URLs Specifics Functions ------------------------------------------------------------
    # path('ventas/detalles/', requestDetallesVentas, name='requestDetallesVentas'),
    # path('ventas/request_ventas/', requestVentasAuditoria, name='requestVentasAuditorias'),

    path('requestmovs/', requestMovimientos, name='rmovs'),
    path('create_new_mov/', createNewMov, name='create_new_mov'),
    #endregion --------------------------------------------------------------------------------

    path("api/cotizaciones/dolar/", cotizaciones_dolar, name="cotizaciones_dolar"),
]

elanelsystem/users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *
 
app_name="users"

urlpatterns = [
    path("usuario/api/me/", me, name="me"),

    path("usuario/crear_usuario/",CrearUsuario.as_view(),name="create_user"),
    path("usuario/search/",requestUsuarios2,name="searchUsers"),

    path("usuario/lista_usuarios/",ListaUsers.as_view(),name="list_users"),
    path("cliente/importUsuarios/",importar_usuarios,name="importUsuarios"),
    path("usuario/aplicar_descuento/",realizarDescuento,name="realizarDescuento"),
    path("usuario/detalleusuario/<int:pk>/",DetailUser.as_view(),name="detailUser"),
    path("cliente/lista_clientes/",ListaClientes.as_view(),name="list_customers"),
    path("cliente/importClientes/",importar_clientes,name="importClientes"),
    path("usuario/administracion/requestusuarios/",requestUsuarios,name="requestUsuarios"),
    path("cliente/crear_cliente/",CrearCliente.as_view(),name="create_customer"),
    path("cliente/<int:pk>/operaciones/",CuentaUser.as_view(),name="cuentaUser"),
    path("usuario/administracion/",PanelAdmin.as_view(),name="panelAdmin"),
    path("usuario/administracion/permisos/",PanelPermisos.as_view(),name="panelPermisos"),
    path("usuario/configurar_perfil/",ConfiguracionPerfil.as_view(),name="configurarPerfil"),


    #region Sucursal CRUD - - - - - - - -
    path("usuario/administracion/sucursales/",PanelSucursales.as_view(),name="panelSucursales"),
    path("usuario/administracion/sucursales/add",addSucursal,name="addSucursal"),
    path("usuario/administracion/sucursales/remove",removeSucursal,name="removeSucursal"),
    path("usuario/administracion/sucursales/update",updateSucursal,name="updateSucursal"),
    #endregion - - - - - - - - - - - - - - 

    #region Cuenta de cobros CRUD - - - - - - - -
    path("usuario/administracion/cuentas_cobros/",PanelCuentaCobro.as_view(),name="panelCuentaDeCobro"),
    path("usuario/administracion/cuentas_cobros/add",addCuenta,name="addCuenta"),
    path("usuario/administracion/cuentas_cobros/remove",removeCuenta,name="removeCuenta"),
    #endregion - - - - - - - - - - - - - - 

    #region Permisos - - - - - - -  - - - - - - - - - - - -
    path("usuario/administracion/requestpermisos/",requestPermisosDeGrupo,name="requestPermisos"),
    path("usuario/administracion/updatepermisos/",updatePermisosAGrupo,name="updatePermisos"),
    path("usuario/administracion/createnewgroup/",createNewGroup,name="newGroup"),
    path("usuario/administracion/deletenewgroup/",deleteGrupo,name="deleteGroup"),
    path("usuario/administracion/requestkey/",requestKey,name="requestKey"),
    #endregion  - - - - - - - - - - - - - - - - - - - - - - - -

    path("usuario/pdf/ficha_creacion/<int:pk>",viewsPDFNewUser,name="newUserPDF"),

]

elanelsystem/liquidacion/models.py
from django.db import models
from users.models import Usuario,Sucursal
from sales.models import Ventas
from django.forms import ValidationError

from datetime import datetime
# from .utils import coeficienteCantidadOrdenadoVendedor, coeficienteProductividadOrdenadoVendedor,getDetalleComisionPorCantVentasPropias,getPremioProductividadVentasPropias,getAusenciasTardanzas,getAdelantos,getAsegurado,calcular_ventas,calcular_productividad

class MontoTardanzaAusencia(models.Model):
    monto_tardanza = models.DecimalField(max_digits=6, decimal_places=2, default=350.00)
    monto_ausencia = models.DecimalField(max_digits=6, decimal_places=2, default=2000.00)
    margen_tiempo = models.IntegerField(default=15)  # Ejemplo: 15 minutos

    # class Meta:
    #     verbose_name = "Monto para tardanza y ausencia"
    #     verbose_name_plural = "Montos para tardanzas y ausencias"

    def save(self, *args, **kwargs):
        # Asegurar que solo exista una instancia
        if not self.pk and MontoTardanzaAusencia.objects.exists():
            raise ValidationError("Solo puede existir una instancia de 'Monto para tardanza y ausencia'.")
        super().save(*args, **kwargs)

    @staticmethod
    def get_solo():
        # Obtener la instancia única
        configuracion, created = MontoTardanzaAusencia.objects.get_or_create()
        return configuracion

class Asegurado(models.Model):
    dinero = models.IntegerField("Dinero")
    dirigido = models.CharField("Dirigido", max_length=80)
    # objetivo = models.IntegerField("Objetivo", default=0)

    def __str__(self):
        return str(self.dinero) + "--" + str(self.dirigido)

class Liquidacion(models.Model):
    agencia = models.ForeignKey(Sucursal, on_delete=models.DO_NOTHING, related_name="liquidacion_agencia")
    campania = models.CharField("Campaña", max_length=50)
    fecha = models.CharField("Fecha", max_length=15)
    json_data_liquidacion = models.JSONField(default=list)

elanelsystem/liquidacion/templates/comisiones.html
{% extends 'molde.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/comisiones.css' %}">
<link rel="stylesheet" href="{% static 'css/root_base.css' %}">
<link rel="stylesheet" href="{% static 'modalStatic/doc/tingle/tingle.min.css' %}">

{% endblock css %}

{% block content %}
    <div id="wrapperLoader">
        <span id="loader"></span>
    </div>

    <div class="wrapperHeader">
        <h3 class="titleHeader">Calculo de comisiones</h3>
        <div class="wrapperInputsSearchs">
            <div id="sucursalWrapper" class="wrapperTypeFilter wrapperSelectCustom inputWrapper">
                <h3 class="labelInput">Sucursal</h3>
                <div class="containerInputAndOptions">
                  <img class="iconDesplegar" src="{% static 'images/icons/arrowDown.png' %}" alt="">
                  <input type="hidden" class="filterInput" name="sucursal" id="sucursalInput" placeholder="Seleccionar" autocomplete="off" readonly>
                  <div class="onlySelect pseudo-input-select-wrapper">
                        <h3></h3>
                  </div>
                  <ul id="contenedorSucursal" class="list-select-custom options">
                    {% for sucursal in sucursales %}
                        <li data-value={{sucursal.id}}>{{sucursal}}</li>
                    {% endfor %}
                </ul>
                </div>
            </div>
            
            <div id="campaniaWrapper" class="wrapperTypeFilter wrapperSelectCustom inputWrapper">
                <h3 class="labelInput">Campaña</h3>
                <div class="containerInputAndOptions">
                  <img class="iconDesplegar" src="{% static 'images/icons/arrowDown.png' %}" alt="">
                  <input type="hidden" class="filterInput" name="campania" id="campaniaInput" placeholder="Seleccionar" autocomplete="off" readonly>
                  <div class="onlySelect pseudo-input-select-wrapper">
                        <h3></h3>
                  </div>
                  <ul id="contenedorCampania" class="list-select-custom options">
                    {% for campania in campanias %}
                            <li data-value="{{campania}}">{{campania}}</li>
                    {% endfor %}
                </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="wrapperManageLiquidacion">
        <div class="colaboradoresWrapper">

                <div class="colaboradores">
                    <div class="listColaboradoresWrapper">
                        <div class="wrapperTittle">
                            <h3>Liquidacion de comisiones</h3>
                            <div class="searchColaboradores">
                                <input type="text" placeholder="Buscar colaborador..." class="input-read-write-default">
                                <img src="{% static 'images/icons/search.svg' %}" alt="search">
                            </div>
                        </div>
                        <div class="tittlesWrapper">
                            <ul class="tittles">
                                <li>Colaborador</li>
                                <li>Cargo</li>
                                <li>Comisión</li>
                                <li>Acciones</li>
                            </ul>   
                        </div>
                
                        <div class="valuesWrapper preValues">
                            
                            <h3 id="textPreValuesColaboradores">Seleccione la sucursal y campaña antes de comenzar</h3>
                            <ul class="values">
                            </ul>       
                        </div>
                    </div>
{% comment %} 
                    <div class="selectTipoColaborador">
                        <div>
                            <input type="radio" name="tipoColaborador" id="todos" value="todos" class="inputSelectTipoColaborador" checked>
                            <label for="todos">Todos</label>
                        </div>
                        <div>
                            <input type="radio" name="tipoColaborador" id="vendedores" value="Vendedor" class="inputSelectTipoColaborador">
                            <label for="vendedores">Vendedores</label>
                        </div>
                        <div>
                            <input type="radio" name="tipoColaborador" id="supervisores" value="Supervisor" class="inputSelectTipoColaborador">
                            <label for="supervisores">Supervisores</label>
                        </div>
                        <div>
                            <input type="radio" name="tipoColaborador" id="gerente_sucursal" value="Gerente sucursal" class="inputSelectTipoColaborador">
                            <label for="gerente_sucursal">Gerentes de sucursal</label>
                        </div>
                    </div> {% endcomment %}
                </div>

                <div class="resumen_actions_wrapper">
                    <div id="totalComisionesTextColaboradores_wrapper">
                        <h2>Total de comisionar</h2>
                        <input type="hidden" id="totalComisionesInput" value="0">
                        <h3><span id="dineroTotalComisiones">$ 0</span></h3>
                    </div>
                    <div class="wrapperButtonsActions hidden" id="wrapperButtonsActions">
                        <a href="{% url 'liquidacion:preViewPDFLiquidacion' %}" id="previsualizarButton" target="_blank">Previsualizar</a>
                        <button type="button" id="liquidarButton" onclick="newModalLiquidacion()">Liquidar</button>
                    </div> 
                </div>
            </div>
    </div>
   
{% endblock content %}
{% block js %}
    <script> 
        var CSRF_TOKEN = '{% csrf_token %}';
        const urlRequestColaboradores = "{{urlRequestColaboradores}}"
        const urlVentasNoComisionables = "{% url 'sales:ventas_comisionables' %}"
        const urlExportDetallesComision = "{% url 'liquidacion:export_comision_excel' %}";

        var info_icon = "{% static 'images/icons/info_icon.svg' %}"
        var export_icon = "{% static 'images/icons/export_icon.svg' %}"

    </script>
    <script src="{% static 'js/vanilla_components/formatMoney.js' %}"></script>
    <script src="{% static 'js/liquidation/redirectToPDFNewLiquidacion.js' %}"></script>
    <script src="{% static 'modalStatic/doc/tingle/tingle.min.js' %}"></script>

    <script src="{% static 'js/liquidation/filters_liquidacion.js' %}"></script>
    <script src="{% static 'js/liquidation/ajuste_comision_liquidacion.js' %}"></script> 
    <script src="{% static 'js/vanilla_components/vanilla_components/z_index_orders_selects.js.js' %}"></script>
    <script src="{% static 'js/vanilla_components/inputSelectOnly_v2.js.js' %}"></script>

    
{% endblock js %}

elanelsystem/liquidacion/templates/detalle_comisiones.html
{% extends 'molde.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/detallesComisiones.css' %}">
<link rel="stylesheet" href="{% static 'css/root_base.css' %}">
<link rel="stylesheet" href="{% static 'modalStatic/doc/tingle/tingle.min.css' %}">

{% endblock css %}

{% block content %}
<div id="wrapperLoader">
  <span id="loader"></span>
</div>

<div class="filters">
  
  <form method="POST" id="formFilter">
    {% csrf_token %}
    <div class="filtersActionWrapper">
        <div id="sucursalWrapper" class="wrapperTypeFilter wrapperSelectCustom inputWrapper">
            <h3 class="labelInput">Sucursal</h3>
            <div class="containerInputAndOptions">
              <img class="iconDesplegar" src="{% static 'images/icons/arrowDown.png' %}" alt="">
              <input type="hidden" class="filterInput" name="agencia" id="sucursalInput" placeholder="Seleccionar" autocomplete="off" readonly>
              <div class="onlySelect pseudo-input-select-wrapper">
                    <h3></h3>
              </div>
              <ul id="contenedorSucursal" class="list-select-custom options">
                {% for sucursal in sucursales %}
                    <li data-value="{{sucursal.id}}">{{sucursal.pseudonimo}}</li>
                {% endfor %}
            </ul>
            </div>
        </div>
        
        <div id="campaniaWrapper" class="wrapperTypeFilter wrapperSelectCustom inputWrapper">
            <h3 class="labelInput">Campaña</h3>
            <div class="containerInputAndOptions">
              <img class="iconDesplegar" src="{% static 'images/icons/arrowDown.png' %}" alt="">
              <input type="hidden" class="filterInput" name="campania" id="campaniaInput" placeholder="Seleccionar" autocomplete="off" readonly>
              <div class="onlySelect pseudo-input-select-wrapper">
                    <h3></h3>
              </div>
              <ul id="contenedorSucursal" class="list-select-custom options">
                {% for campania in campanias %}
                        <li data-value="{{campania}}">{{campania}}</li>
                {% endfor %}
            </ul>
            </div>
        </div>
    </div>
    
  </form>   
  <div class="buttonsActionsWrapper">
    {% comment %} <button type="button" id="showModalFiltro" class="button-default-style" onclick="newModalIFiltro()">Exportar</button> {% endcomment %}
    <a href="{% url 'exportExcel' %}" id="buttonExport" class="add-button-default" >Exportar a Excel</a>
  </div>
</div>



<div class="informationWrapper">
  <a href="{% url 'users:list_customers'%}" id="buttonCleanFilter">Limpiar filtros</a>
  <div class="tableWrapper">
    <table class="informationTable">
      <thead>
          <tr>
              {% for key, value  in data.0.items %}
                <th>{{ value.verbose_name }}</th>
              {% endfor %}
            
          </tr>
      </thead>
      <tbody>
          {% for d in data %}
              <tr>
                {% for key, value  in d.items %}
                  <td>{{ value.data }}</td>
                {% endfor %}
              </tr>
          {% endfor %}
      </tbody>
    </table>
  </div>
</div> 

<div class="paginationWrapper">
  {% if data.has_previous %}
      <button class="buttonsPagesManage" id="previouPageButton" value="{{ data.previous_page_number }}">Anterior</button>
  {%else%}
      <button class="buttonsPagesManage" id="previouPageButton" value="1" disabled>Anterior</button>
  {% endif %}

  <span id="textPaginator">Página {{ data.number }} de {{ data.paginator.num_pages }}</span>

   {% if data.has_next %} 
      <button class="buttonsPagesManage" id="nextPageButton" value="{{ data.next_page_number }}">Siguiente</button>
   {%else%}
      <button class="buttonsPagesManage" id="nextPageButton" value="{{ data.paginator.num_pages }}" disabled>Siguiente</button>
    {% endif %} 
</div>

{% endblock content %}
{% block js %}
<script>
  var csrf_token = '{%csrf_token%}'
  var urlImportData = "{% url 'users:importClientes' %}"
  var sucursalesDisponibles = {{ sucursalesDisponiblesJSON|safe }};
  var logoDisplayMore = "{% static 'images/icons/arrowDown.png' %}";
  var tipoSlug = "{{ tipo }}";
</script>



<script src="{% static 'modalStatic/doc/tingle/tingle.min.js' %}"></script>
<script src="{% static 'js/vanilla_components/vanilla_components/z_index_orders_selects.js.js' %}"></script>
<script src="{% static 'js/vanilla_components/inputSelectOnly_v2.js.js' %}"></script>



{% endblock js %}

elanelsystem/liquidacion/templates/liquidaciones_panel.html
{% extends 'molde.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/panel_liquidaciones.css' %}">
{% endblock css %}

{% block content %}
    <div class="wrapperSections">
        <div class ="tittleWrapper">
            <h4>Liquidar<h4>
        </div>
        <div class="buttonWrapper">
            <a href="{% url 'liquidacion:liquidacionesComisiones' %}" class="buttonMore">
                <div>
                    <h3>Ir</h3>
                    <img src="{% static 'images/icons/nextSinBackground.png' %}" alt="">
                </div>
            </a>
        </div>
    </div>
    
    <div class="wrapperSections">
        <div class ="tittleWrapper">
            <h4>Ranking<h4>
        </div>
        <div class="buttonWrapper">
            <a href="{% url 'liquidacion:liquidacionesRanking' %}" class="buttonMore">
                <div>
                    <h3>Ir</h3>
                    <img src="{% static 'images/icons/nextSinBackground.png' %}" alt="">
                </div>
            </a>
        </div>
    </div>

    <div class="wrapperSections">
        <div class ="tittleWrapper">
            <h4>Detalle de ventas <h4>
        </div>
        <div class="buttonWrapper">
            <a href="{% url 'liquidacion:detallesComisionesView' 'ventas' %}" class="buttonMore">
                <div>
                    <h3>Ir</h3>
                    <img src="{% static 'images/icons/nextSinBackground.png' %}" alt="">
                </div>
            </a>    
        </div>
               
    </div>
    
    <div class="wrapperSections">
        <div class ="tittleWrapper">
            <h4>Cuotas 1 adelantadas<h4>
        </div>
        <div class="buttonWrapper">
            <a href="{% url 'liquidacion:detallesComisionesView' 'cuotas_1' %}" class="buttonMore">
                <div>
                    <h3>Ir</h3>
                    <img src="{% static 'images/icons/nextSinBackground.png' %}" alt="">
                </div>
            </a>
        </div>
    </div>

    <div class="wrapperSections">
        <div class ="tittleWrapper">
            <h4>Ausencias y tardanzas<h4>
        </div>
        <div class="buttonWrapper">
            <a href="{% url 'liquidacion:liquidacionesAusenciaYTardanzas' %}" class="buttonMore">
                <div>
                    <h3>Ir</h3>
                    <img src="{% static 'images/icons/nextSinBackground.png' %}" alt="">
                </div>
            </a>
        </div>
    </div>
    {% comment %} <div class="wrapperSections">
        <div class ="tittleWrapper">
            <h4>Tabla de porcentajes<h4>
        </div>
        <div class="buttonWrapper">
            <a href="#" class="buttonMore">
                <div>
                    <h3>Ir</h3>
                    <img src="{% static 'images/icons/nextSinBackground.png' %}" alt="">
                </div>
            </a>
        </div>
    </div> {% endcomment %}
    <div class="wrapperSections">
        <div class ="tittleWrapper">
            <h4>Historial de liquidaciones<h4>
        </div>
        <div class="buttonWrapper">
            <a href="{% url  'liquidacion:historialLiquidaciones' %}" class="buttonMore">
                <div>
                    <h3>Ir</h3>
                    <img src="{% static 'images/icons/nextSinBackground.png' %}" alt="">
                </div>
            </a>
        </div>
    </div>

{% endblock content %}
{% block js %}
    
{% endblock js %}